module.exports = [
	{
		country: 'Vietnam',
		continent: 'Asia',
		rating: 2,
		image: 'https://i.imgur.com/uoDoVxs.jpeg',
	},
	{ country: 'Armenia', continent: 'Europe', rating: 4, image: '' },
	{
		country: 'Sweden',
		continent: 'Europe',
		rating: 2,
		image: 'https://i.imgur.com/9qyJz8I.jpeg',
	},
	{
		country: 'France',
		continent: 'Europe',
		rating: 3,
		image: 'https://i.imgur.com/fZOvGSF.jpeg',
	},
	{
		image: 'https://i.imgur.com/Z8vxkzy.jpeg',
		country: 'Portugal',
		continent: 'Europe',
		rating: 5,
	},
	{
		image: 'https://i.imgur.com/NHsLeO4.jpeg',
		country: 'Egypt',
		continent: 'Africa',
		rating: 3,
	},
	{
		image: 'https://i.imgur.com/9ux1vvM.jpeg',
		country: 'United States',
		continent: 'North America',
		rating: 4,
	},
	{
		image: 'https://i.imgur.com/ziYpmXm.jpeg',
		country: 'Peru',
		continent: 'South America',
		rating: 3,
	},
	{
		image: 'https://i.imgur.com/i8KA2HC.jpeg',
		country: 'Chile',
		continent: 'South America',
		rating: 2,
	},
	{
		image: 'https://i.imgur.com/MGxkFrG.jpeg',
		country: 'Moldova',
		continent: 'Europe',
		rating: 3,
	},
	{
		image: 'https://i.imgur.com/5LPFBIX.jpeg',
		country: 'Botswana',
		continent: 'Africa',
		rating: 3,
	},
	{
		image: 'https://i.imgur.com/fZOvGSF.jpeg',
		country: 'France',
		continent: 'Europe',
		rating: 1,
	},
	{
		image: 'https://i.imgur.com/v7t3QsC.jpeg',
		country: 'Honduras',
		continent: 'South America',
		rating: 3,
	},
	{
		image: 'https://i.imgur.com/aSOwnNf.jpeg',
		country: 'China',
		continent: 'Asia',
		rating: 1,
	},
	{
		image: 'https://i.imgur.com/5LPFBIX.jpeg',
		country: 'China',
		continent: 'Asia',
		rating: 5,
	},
	{
		image: 'https://i.imgur.com/ACTEZ8U.jpeg',
		country: 'China',
		continent: 'Asia',
		rating: 1,
	},
	{
		image: 'https://i.imgur.com/3ZoVtZ9.jpeg',
		country: 'China',
		continent: 'Asia',
		rating: 3,
	},
	{
		image: 'https://i.imgur.com/NdCi9al.jpeg',
		country: 'China',
		continent: 'Asia',
		rating: 4,
	},
	{
		image: 'https://i.imgur.com/1RqHSb0.jpeg',
		country: 'China',
		continent: 'Asia',
		rating: 3,
	},
	{
		image: 'https://i.imgur.com/nTTVE3s.jpeg',
		country: 'China',
		continent: 'Asia',
		rating: 1,
	},
	{
		image: 'https://i.imgur.com/MGxkFrG.jpeg',
		country: 'Poland',
		continent: 'Europe',
		rating: 5,
	},
	{
		image: 'https://i.imgur.com/AfDDE0z.jpeg',
		country: 'Indonesia',
		continent: 'Asia',
		rating: 3,
	},
	{
		image: 'https://i.imgur.com/25ppNN4.jpeg',
		country: 'Indonesia',
		continent: 'Asia',
		rating: 5,
	},
	{
		image: 'https://i.imgur.com/1dL6amm.jpeg',
		country: 'Indonesia',
		continent: 'Asia',
		rating: 5,
	},
	{
		image: 'https://i.imgur.com/Wv52oFy.jpeg',
		country: 'Indonesia',
		continent: 'Asia',
		rating: 4,
	},
	{
		image: 'https://i.imgur.com/V2mvnhY.jpeg',
		country: 'Indonesia',
		continent: 'Asia',
		rating: 3,
	},
	{
		image: 'https://i.imgur.com/NHsLeO4.jpeg',
		country: 'Indonesia',
		continent: 'Asia',
		rating: 2,
	},
	{
		image: 'https://i.imgur.com/MGxkFrG.jpeg',
		country: 'Poland',
		continent: 'Europe',
		rating: 2,
	},
	{
		image: 'https://i.imgur.com/mucvA3M.jpeg',
		country: 'Poland',
		continent: 'Europe',
		rating: 5,
	},
	{
		image: 'https://i.imgur.com/WOlTiZ8.jpeg',
		country: 'Portugal',
		continent: 'Europe',
		rating: 1,
	},
	{
		image: 'https://i.imgur.com/il2OmH0.jpeg',
		country: 'Portugal',
		continent: 'Europe',
		rating: 3,
	},
	{
		image: 'https://i.imgur.com/fZOvGSF.jpeg',
		country: 'France',
		continent: 'Europe',
		rating: 3,
	},
];
